[Update] : update the workflow file

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -1,4 +1,3 @@
-
 name: Playwright Tests
 
 on:
@@ -16,7 +15,6 @@ on:
 
   push:
     branches: [main, master, Day06-POM_Architecture, Day07-Environment_Configuration, Final_Assignment]
-
   pull_request:
     branches: [main, master, Day06-POM_Architecture, Day07-Environment_Configuration, Final_Assignment]
 
@@ -26,17 +24,24 @@ jobs:
 
     env:
       TEST_ENV: ${{ github.event.inputs.test_env || 'qa' }}
+      PRODUCT_NAME: ${{ vars.PRODUCT_NAME }}
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Verify env file exists
+      - name: Set BASE_URL by environment
         run: |
-          echo "TEST_ENV=$TEST_ENV"
-          ls -la
-          test -f ".env.$TEST_ENV" || exit 1
-
+          if [ "${TEST_ENV}" = "dev" ]; then
+            echo "BASE_URL=${{ secrets.DEV_BASE_URL }}" >> $GITHUB_ENV
+          elif [ "${TEST_ENV}" = "qa" ]; then
+            echo "BASE_URL=${{ secrets.QA_BASE_URL }}" >> $GITHUB_ENV
+          elif [ "${TEST_ENV}" = "stage" ]; then
+            echo "BASE_URL=${{ secrets.STAGE_BASE_URL }}" >> $GITHUB_ENV
+          else
+            echo "Invalid TEST_ENV: ${TEST_ENV}"
+            exit 1
+          fi
       - name: Setup Node.js
         uses: actions/setup-node@v4
         with:
@@ -50,7 +55,7 @@ jobs:
         run: npx playwright install --with-deps
 
       - name: Run Playwright tests
-        run: npx playwright test
+        run: TEST_ENV=${{ github.event.inputs.environment }} npx playwright test
 
       - name: Upload Playwright HTML report
         if: always()
