[Add] : add custom fixture, environment configuration

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -1,18 +1,47 @@
 name: Playwright Tests
 
 on:
+  workflow_dispatch:
+    inputs:
+      test_env:
+        description: "Select environment"
+        required: true
+        default: "qa"
+        type: choice
+        options:
+          - dev
+          - qa
+          - stage
+
   push:
-    branches: [main, master, Day06-POM_Architecture]
+    branches: [main, master, Day06-POM_Architecture, Day07-Environment_Configuration]
   pull_request:
-    branches: [main, master, Day06-POM_Architecture]
+    branches: [main, master, Day06-POM_Architecture, Day07-Environment_Configuration]
 
 jobs:
   test:
     runs-on: ubuntu-latest
 
+    env:
+      TEST_ENV: ${{ github.event.inputs.test_env || 'qa' }}
+      PRODUCT_NAME: ${{ vars.PRODUCT_NAME }}
+
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+
+      - name: Set BASE_URL by environment
+        run: |
+          if [ "${TEST_ENV}" = "dev" ]; then
+            echo "BASE_URL=${{ secrets.DEV_BASE_URL }}" >> $GITHUB_ENV
+          elif [ "${TEST_ENV}" = "qa" ]; then
+            echo "BASE_URL=${{ secrets.QA_BASE_URL }}" >> $GITHUB_ENV
+          elif [ "${TEST_ENV}" = "stage" ]; then
+            echo "BASE_URL=${{ secrets.STAGE_BASE_URL }}" >> $GITHUB_ENV
+          else
+            echo "Invalid TEST_ENV: ${TEST_ENV}"
+            exit 1
+          fi
 
       - name: Setup Node.js
         uses: actions/setup-node@v4
@@ -33,6 +62,6 @@ jobs:
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: playwright-report
+          name: playwright-report-${{ env.TEST_ENV }}
           path: playwright-report/
           retention-days: 30
